spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/questapp
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true